//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CRM_DataBaseModel", "FK_Pessoa_fisica", "Pessoa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TecWeb_CRM.CRM.Dao.Pessoa), "Pessoa_Fisica", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TecWeb_CRM.CRM.Dao.Pessoa_Fisica), true)]
[assembly: EdmRelationshipAttribute("CRM_DataBaseModel", "FK_Pessoa_juridica", "Pessoa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TecWeb_CRM.CRM.Dao.Pessoa), "Pessoa_Juridica", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TecWeb_CRM.CRM.Dao.Pessoa_Juridica), true)]
[assembly: EdmRelationshipAttribute("CRM_DataBaseModel", "FK_Agenda_Pessoa", "Pessoa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TecWeb_CRM.CRM.Dao.Pessoa), "Agendum", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TecWeb_CRM.CRM.Dao.Agendum), true)]

#endregion

namespace TecWeb_CRM.CRM.Dao
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CRM_DataBaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CRM_DataBaseEntities object using the connection string found in the 'CRM_DataBaseEntities' section of the application configuration file.
        /// </summary>
        public CRM_DataBaseEntities() : base("name=CRM_DataBaseEntities", "CRM_DataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CRM_DataBaseEntities object.
        /// </summary>
        public CRM_DataBaseEntities(string connectionString) : base(connectionString, "CRM_DataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CRM_DataBaseEntities object.
        /// </summary>
        public CRM_DataBaseEntities(EntityConnection connection) : base(connection, "CRM_DataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pessoa> Pessoas
        {
            get
            {
                if ((_Pessoas == null))
                {
                    _Pessoas = base.CreateObjectSet<Pessoa>("Pessoas");
                }
                return _Pessoas;
            }
        }
        private ObjectSet<Pessoa> _Pessoas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pessoa_Fisica> Pessoa_Fisica
        {
            get
            {
                if ((_Pessoa_Fisica == null))
                {
                    _Pessoa_Fisica = base.CreateObjectSet<Pessoa_Fisica>("Pessoa_Fisica");
                }
                return _Pessoa_Fisica;
            }
        }
        private ObjectSet<Pessoa_Fisica> _Pessoa_Fisica;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pessoa_Juridica> Pessoa_Juridica
        {
            get
            {
                if ((_Pessoa_Juridica == null))
                {
                    _Pessoa_Juridica = base.CreateObjectSet<Pessoa_Juridica>("Pessoa_Juridica");
                }
                return _Pessoa_Juridica;
            }
        }
        private ObjectSet<Pessoa_Juridica> _Pessoa_Juridica;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Agendum> Agenda
        {
            get
            {
                if ((_Agenda == null))
                {
                    _Agenda = base.CreateObjectSet<Agendum>("Agenda");
                }
                return _Agenda;
            }
        }
        private ObjectSet<Agendum> _Agenda;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pessoas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPessoas(Pessoa pessoa)
        {
            base.AddObject("Pessoas", pessoa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pessoa_Fisica EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPessoa_Fisica(Pessoa_Fisica pessoa_Fisica)
        {
            base.AddObject("Pessoa_Fisica", pessoa_Fisica);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pessoa_Juridica EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPessoa_Juridica(Pessoa_Juridica pessoa_Juridica)
        {
            base.AddObject("Pessoa_Juridica", pessoa_Juridica);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Agenda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAgenda(Agendum agendum)
        {
            base.AddObject("Agenda", agendum);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRM_DataBaseModel", Name="Agendum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Agendum : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Agendum object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="data">Initial value of the data property.</param>
        /// <param name="hora">Initial value of the hora property.</param>
        public static Agendum CreateAgendum(global::System.Int32 id, global::System.String data, global::System.String hora)
        {
            Agendum agendum = new Agendum();
            agendum.ID = id;
            agendum.data = data;
            agendum.hora = hora;
            return agendum;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.String _data;
        partial void OndataChanging(global::System.String value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String hora
        {
            get
            {
                return _hora;
            }
            set
            {
                OnhoraChanging(value);
                ReportPropertyChanging("hora");
                _hora = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("hora");
                OnhoraChanged();
            }
        }
        private global::System.String _hora;
        partial void OnhoraChanging(global::System.String value);
        partial void OnhoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comentario
        {
            get
            {
                return _comentario;
            }
            set
            {
                OncomentarioChanging(value);
                ReportPropertyChanging("comentario");
                _comentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comentario");
                OncomentarioChanged();
            }
        }
        private global::System.String _comentario;
        partial void OncomentarioChanging(global::System.String value);
        partial void OncomentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FK_Pessoa
        {
            get
            {
                return _FK_Pessoa;
            }
            set
            {
                OnFK_PessoaChanging(value);
                ReportPropertyChanging("FK_Pessoa");
                _FK_Pessoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Pessoa");
                OnFK_PessoaChanged();
            }
        }
        private Nullable<global::System.Int32> _FK_Pessoa;
        partial void OnFK_PessoaChanging(Nullable<global::System.Int32> value);
        partial void OnFK_PessoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Data_Email
        {
            get
            {
                return _Data_Email;
            }
            set
            {
                OnData_EmailChanging(value);
                ReportPropertyChanging("Data_Email");
                _Data_Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data_Email");
                OnData_EmailChanged();
            }
        }
        private global::System.String _Data_Email;
        partial void OnData_EmailChanging(global::System.String value);
        partial void OnData_EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hora_Email
        {
            get
            {
                return _Hora_Email;
            }
            set
            {
                OnHora_EmailChanging(value);
                ReportPropertyChanging("Hora_Email");
                _Hora_Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hora_Email");
                OnHora_EmailChanged();
            }
        }
        private global::System.String _Hora_Email;
        partial void OnHora_EmailChanging(global::System.String value);
        partial void OnHora_EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cod_Tipo
        {
            get
            {
                return _Cod_Tipo;
            }
            set
            {
                OnCod_TipoChanging(value);
                ReportPropertyChanging("Cod_Tipo");
                _Cod_Tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cod_Tipo");
                OnCod_TipoChanged();
            }
        }
        private Nullable<global::System.Int32> _Cod_Tipo;
        partial void OnCod_TipoChanging(Nullable<global::System.Int32> value);
        partial void OnCod_TipoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRM_DataBaseModel", "FK_Agenda_Pessoa", "Pessoa")]
        public Pessoa Pessoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Agenda_Pessoa", "Pessoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Agenda_Pessoa", "Pessoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pessoa> PessoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Agenda_Pessoa", "Pessoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Agenda_Pessoa", "Pessoa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRM_DataBaseModel", Name="Pessoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pessoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pessoa object.
        /// </summary>
        /// <param name="codPessoa">Initial value of the CodPessoa property.</param>
        public static Pessoa CreatePessoa(global::System.Int32 codPessoa)
        {
            Pessoa pessoa = new Pessoa();
            pessoa.CodPessoa = codPessoa;
            return pessoa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodPessoa
        {
            get
            {
                return _CodPessoa;
            }
            set
            {
                if (_CodPessoa != value)
                {
                    OnCodPessoaChanging(value);
                    ReportPropertyChanging("CodPessoa");
                    _CodPessoa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodPessoa");
                    OnCodPessoaChanged();
                }
            }
        }
        private global::System.Int32 _CodPessoa;
        partial void OnCodPessoaChanging(global::System.Int32 value);
        partial void OnCodPessoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuário
        {
            get
            {
                return _usuário;
            }
            set
            {
                OnusuárioChanging(value);
                ReportPropertyChanging("usuário");
                _usuário = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuário");
                OnusuárioChanged();
            }
        }
        private global::System.String _usuário;
        partial void OnusuárioChanging(global::System.String value);
        partial void OnusuárioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRM_DataBaseModel", "FK_Pessoa_fisica", "Pessoa_Fisica")]
        public EntityCollection<Pessoa_Fisica> Pessoa_Fisica
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pessoa_Fisica>("CRM_DataBaseModel.FK_Pessoa_fisica", "Pessoa_Fisica");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pessoa_Fisica>("CRM_DataBaseModel.FK_Pessoa_fisica", "Pessoa_Fisica", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRM_DataBaseModel", "FK_Pessoa_juridica", "Pessoa_Juridica")]
        public EntityCollection<Pessoa_Juridica> Pessoa_Juridica
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pessoa_Juridica>("CRM_DataBaseModel.FK_Pessoa_juridica", "Pessoa_Juridica");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pessoa_Juridica>("CRM_DataBaseModel.FK_Pessoa_juridica", "Pessoa_Juridica", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRM_DataBaseModel", "FK_Agenda_Pessoa", "Agendum")]
        public EntityCollection<Agendum> Agenda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Agendum>("CRM_DataBaseModel.FK_Agenda_Pessoa", "Agendum");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Agendum>("CRM_DataBaseModel.FK_Agenda_Pessoa", "Agendum", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRM_DataBaseModel", Name="Pessoa_Fisica")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pessoa_Fisica : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pessoa_Fisica object.
        /// </summary>
        /// <param name="codPessoaF">Initial value of the CodPessoaF property.</param>
        public static Pessoa_Fisica CreatePessoa_Fisica(global::System.Int32 codPessoaF)
        {
            Pessoa_Fisica pessoa_Fisica = new Pessoa_Fisica();
            pessoa_Fisica.CodPessoaF = codPessoaF;
            return pessoa_Fisica;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodPessoaF
        {
            get
            {
                return _CodPessoaF;
            }
            set
            {
                if (_CodPessoaF != value)
                {
                    OnCodPessoaFChanging(value);
                    ReportPropertyChanging("CodPessoaF");
                    _CodPessoaF = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodPessoaF");
                    OnCodPessoaFChanged();
                }
            }
        }
        private global::System.Int32 _CodPessoaF;
        partial void OnCodPessoaFChanging(global::System.Int32 value);
        partial void OnCodPessoaFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodPessoa
        {
            get
            {
                return _CodPessoa;
            }
            set
            {
                OnCodPessoaChanging(value);
                ReportPropertyChanging("CodPessoa");
                _CodPessoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodPessoa");
                OnCodPessoaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodPessoa;
        partial void OnCodPessoaChanging(Nullable<global::System.Int32> value);
        partial void OnCodPessoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cpf
        {
            get
            {
                return _Cpf;
            }
            set
            {
                OnCpfChanging(value);
                ReportPropertyChanging("Cpf");
                _Cpf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cpf");
                OnCpfChanged();
            }
        }
        private global::System.String _Cpf;
        partial void OnCpfChanging(global::System.String value);
        partial void OnCpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRM_DataBaseModel", "FK_Pessoa_fisica", "Pessoa")]
        public Pessoa Pessoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_fisica", "Pessoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_fisica", "Pessoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pessoa> PessoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_fisica", "Pessoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_fisica", "Pessoa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRM_DataBaseModel", Name="Pessoa_Juridica")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pessoa_Juridica : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pessoa_Juridica object.
        /// </summary>
        /// <param name="codPessoaj">Initial value of the CodPessoaj property.</param>
        public static Pessoa_Juridica CreatePessoa_Juridica(global::System.Int32 codPessoaj)
        {
            Pessoa_Juridica pessoa_Juridica = new Pessoa_Juridica();
            pessoa_Juridica.CodPessoaj = codPessoaj;
            return pessoa_Juridica;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodPessoaj
        {
            get
            {
                return _CodPessoaj;
            }
            set
            {
                if (_CodPessoaj != value)
                {
                    OnCodPessoajChanging(value);
                    ReportPropertyChanging("CodPessoaj");
                    _CodPessoaj = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodPessoaj");
                    OnCodPessoajChanged();
                }
            }
        }
        private global::System.Int32 _CodPessoaj;
        partial void OnCodPessoajChanging(global::System.Int32 value);
        partial void OnCodPessoajChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodPessoa
        {
            get
            {
                return _CodPessoa;
            }
            set
            {
                OnCodPessoaChanging(value);
                ReportPropertyChanging("CodPessoa");
                _CodPessoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodPessoa");
                OnCodPessoaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodPessoa;
        partial void OnCodPessoaChanging(Nullable<global::System.Int32> value);
        partial void OnCodPessoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cnpj
        {
            get
            {
                return _Cnpj;
            }
            set
            {
                OnCnpjChanging(value);
                ReportPropertyChanging("Cnpj");
                _Cnpj = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cnpj");
                OnCnpjChanged();
            }
        }
        private global::System.String _Cnpj;
        partial void OnCnpjChanging(global::System.String value);
        partial void OnCnpjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazaoSocial
        {
            get
            {
                return _RazaoSocial;
            }
            set
            {
                OnRazaoSocialChanging(value);
                ReportPropertyChanging("RazaoSocial");
                _RazaoSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazaoSocial");
                OnRazaoSocialChanged();
            }
        }
        private global::System.String _RazaoSocial;
        partial void OnRazaoSocialChanging(global::System.String value);
        partial void OnRazaoSocialChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRM_DataBaseModel", "FK_Pessoa_juridica", "Pessoa")]
        public Pessoa Pessoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_juridica", "Pessoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_juridica", "Pessoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pessoa> PessoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_juridica", "Pessoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pessoa>("CRM_DataBaseModel.FK_Pessoa_juridica", "Pessoa", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
